#set(TOOLCHAIN_NAME "watcom-dos32" CACHE STRING "Toolchain name")

set(CMAKE_SYSTEM_NAME "dos")
set(CMAKE_SYSTEM_PROCESSOR "X86")
set(CMAKE_C_COMPILER "wcl386")
set(CMAKE_CXX_COMPILER "wcl386")

set(CMAKE_WATCOM_RUNTIME_LIBRARY "SingleThreaded")

set(CMAKE_C_FLAGS   "-D__DOS__ ${CMAKE_C_FLAGS}")
set(CMAKE_CXX_FLAGS "-D__DOS__ ${CMAKE_CXX_FLAGS}")
